name: C/C++ CI

on: [push]

jobs:
  test:
    name: Building ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest,macOS-latest]
    steps:
      - uses: actions/checkout@v1
      - name: cmake
        run: mkdir build; cd build ; cmake  ..
      - name: make
        run: cd build; make
