name: C/C++ CI

on: [push]

jobs:
  test:
    name: Building ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest,macOS-latest]
    steps:
      - uses: actions/checkout@v1
      - name: cmake macos
        if: matrix.os == 'macOS-latest' 
        run: mkdir build; cd build ; echo "MAC"
      - name: cmake linux
        if: matrix.os == 'ubuntu-latest' 
        run: mkdir build; cd build ; cmake  ..
      - name: make
        if: matrix.os == 'ubuntu-latest' 
        run: cd build; make
